version: '2.4'
services:
    servicetier-first:
        image: "myservicetier"
        environment:
            - databaseServer=${DATABASE_SERVER}
            - databaseInstance=
            - databaseName=${DATABASE_NAME}
            - databaseUserName=${DATABASE_USERNAME}
            - databasePassword=${DATABASE_PASSWORD}
            - encryptionSecurePassword=${ENCRYPTION_SECURE_PASSWORD}
            - encryptionKeyURL=${ENCRYPTION_KEY_URL}
        mem_limit: 4G
    servicetier-second:
        image: "myservicetier"
        environment:
            - databaseServer=${DATABASE_SERVER}
            - databaseInstance=
            - databaseName=${DATABASE_NAME}
            - databaseUserName=${DATABASE_USERNAME}
            - databasePassword=${DATABASE_PASSWORD}
            - encryptionSecurePassword=${ENCRYPTION_SECURE_PASSWORD}
            - encryptionKeyURL=${ENCRYPTION_KEY_URL}
        mem_limit: 4G