version: '2.4'
services:
    servicetierfirst:
        image: "myservicetier"
        environment:
            - databaseServer=${DATABASE_SERVER}
            - databaseInstance=
            - databaseName=${DATABASE_NAME}
            - databaseUserName=${DATABASE_USERNAME}
            - databasePassword=${DATABASE_PASSWORD}
            - encryptionSecurePassword=${ENCRYPTION_SECURE_PASSWORD}
            - encryptionKeyURL=${ENCRYPTION_KEY_URL}
            - publicDnsName=${PUBLIC_DNS_NAME}
            - certificatePfxFileUrl=${CERTIFICATE_PFX_FILE_URL}
            - certificatePfxPassword=${CERTIFICATE_PFX_PASSWORD}
        mem_limit: 4G
    servicetiersecond:
        image: "myservicetier"
        environment:
            - databaseServer=${DATABASE_SERVER}
            - databaseInstance=
            - databaseName=${DATABASE_NAME}
            - databaseUserName=${DATABASE_USERNAME}
            - databasePassword=${DATABASE_PASSWORD}
            - encryptionSecurePassword=${ENCRYPTION_SECURE_PASSWORD}
            - encryptionKeyURL=${ENCRYPTION_KEY_URL}
            - publicDnsName=${PUBLIC_DNS_NAME}
            - certificatePfxFileUrl=${CERTIFICATE_PFX_FILE_URL}
            - certificatePfxPassword=${CERTIFICATE_PFX_PASSWORD}
        mem_limit: 4G
    webclient:
        image: "mywebclient"
        environment:
            - navServer=servicetierfirst
            - navServerInstance=BC
            - publicDnsName=${PUBLIC_DNS_NAME}
            - certificatePfxFileUrl=${CERTIFICATE_PFX_FILE_URL}
            - certificatePfxPassword=${CERTIFICATE_PFX_PASSWORD}
        depends_on: 
            - servicetierfirst